version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    runtime: nvidia  # Specify the GPU runtime
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Specify which GPUs are accessible inside the container

